# Content for the case-study pages in /work/<slug>/.
# English is the source; ar/de/it are translations of the same keys.
# Facts come from each project's source code. Rebuild with: python3 tools/build_cases.py

CASES = [
 {
  'slug': 'amarina', 'shot': 'amarina', 'name': 'Amarina', 'acc': '#FF2733', 'pick': 'web',
  'url': '/amarina.html', 'urlLabel': 'seifabas.vercel.app/amarina',
  'langs': 'EN · AR · NL · DE · PL · CS · FR · RU',
  'nums': ['8', '4', '5', '7'],
  'swatches': [('#0A0608', 'c1'), ('#FF2733', 'c2'), ('#7A0511', 'c3')],
  'fonts': ['Playfair Display', 'Inter'],
  'tech': ['HTML', 'CSS', 'JavaScript', 'Web app manifest', 'Vercel'],
  'en': {
   'type': 'Resort guest web app',
   'lede': 'A guest web app for a five-star resort and aqua park in Marsa Alam: dining, activities and the evening programme in eight languages.',
   'client': 'Amarina Jannah Resort &amp; Aqua Park', 'where': 'Marsa Alam, Red Sea',
   'brief': 'Guests arrive from all over Europe and need one place on their phone for restaurants, opening times, activities and tonight’s show, in their own language and with no app to download.',
   'built': 'A fast web app that installs from the browser. Every restaurant and bar shows whether it is open right now, the evening programme has a card for each night, and the gallery uses the resort’s real photography. WhatsApp is one tap away on every screen.',
   'f1.h': 'Eight languages', 'f1.p': 'English, Arabic, Dutch, German, Polish, Czech, French and Russian, with a right-to-left layout for Arabic.',
   'f2.h': 'Live opening status', 'f2.p': 'Each restaurant and bar shows Open or Closed from the current time, refreshed every minute.',
   'f3.h': 'Evening programme', 'f3.p': 'One card for each night of the week, so guests can plan their stay around the shows.',
   'f4.h': 'Dining guide', 'f4.p': 'Restaurants and bars in two tabs, with cuisine, location and meal times.',
   'f5.h': 'Add to home screen', 'f5.p': 'Installs like an app straight from the browser. No app store needed.',
   'f6.h': 'WhatsApp contact', 'f6.p': 'A floating button and a contact card for questions and requests.',
   'n1': 'Languages', 'n2': 'Restaurants', 'n3': 'Bars', 'n4': 'Evening shows a week',
   'c1': 'Night', 'c2': 'Signature red', 'c3': 'Deep red',
  },
  'ar': {
   'type': 'تطبيق ويب لضيوف المنتجع',
   'lede': 'تطبيق ويب لضيوف منتجع وأكوا بارك خمس نجوم في مرسى علم: المطاعم والأنشطة وبرنامج المساء بثماني لغات.',
   'client': 'أمارينا جنة ريزورت وأكوا بارك', 'where': 'مرسى علم، البحر الأحمر',
   'brief': 'يأتي الضيوف من كل أنحاء أوروبا ويحتاجون مكانًا واحدًا على هواتفهم للمطاعم ومواعيدها والأنشطة وعرض الليلة، بلغتهم ومن دون تحميل أي تطبيق.',
   'built': 'تطبيق ويب سريع يُثبَّت من المتصفح مباشرة. كل مطعم وبار يُظهر إن كان مفتوحًا الآن، ولبرنامج المساء بطاقة لكل ليلة، والمعرض يستخدم صور المنتجع الحقيقية. وواتساب على بُعد لمسة من كل شاشة.',
   'f1.h': 'ثماني لغات', 'f1.p': 'الإنجليزية والعربية والهولندية والألمانية والبولندية والتشيكية والفرنسية والروسية، مع اتجاه من اليمين لليسار للعربية.',
   'f2.h': 'حالة الفتح مباشرة', 'f2.p': 'كل مطعم وبار يظهر مفتوحًا أو مغلقًا حسب الوقت الحالي، ويتحدّث كل دقيقة.',
   'f3.h': 'برنامج المساء', 'f3.p': 'بطاقة لكل ليلة من الأسبوع ليخطط الضيوف إقامتهم حول العروض.',
   'f4.h': 'دليل المطاعم', 'f4.p': 'المطاعم والبارات في تبويبين، مع نوع المطبخ والمكان ومواعيد الوجبات.',
   'f5.h': 'إضافة للشاشة الرئيسية', 'f5.p': 'يُثبَّت كتطبيق مباشرة من المتصفح، بلا متجر تطبيقات.',
   'f6.h': 'تواصل عبر واتساب', 'f6.p': 'زر عائم وبطاقة تواصل للأسئلة والطلبات.',
   'n1': 'لغات', 'n2': 'مطاعم', 'n3': 'بارات', 'n4': 'عروض مسائية أسبوعيًا',
   'c1': 'ليل', 'c2': 'الأحمر المميز', 'c3': 'أحمر داكن',
  },
  'de': {
   'type': 'Web-App für Resortgäste',
   'lede': 'Eine Gäste-Web-App für ein Fünf-Sterne-Resort mit Aquapark in Marsa Alam: Restaurants, Aktivitäten und Abendprogramm in acht Sprachen.',
   'client': 'Amarina Jannah Resort &amp; Aqua Park', 'where': 'Marsa Alam, Rotes Meer',
   'brief': 'Die Gäste kommen aus ganz Europa und brauchen einen Ort auf dem Handy für Restaurants, Öffnungszeiten, Aktivitäten und die Show des Abends, in ihrer Sprache und ohne App-Download.',
   'built': 'Eine schnelle Web-App, die sich direkt aus dem Browser installieren lässt. Jedes Restaurant und jede Bar zeigt, ob gerade geöffnet ist, das Abendprogramm hat eine Karte pro Abend, und die Galerie zeigt echte Fotos des Resorts. WhatsApp ist auf jedem Bildschirm nur einen Tipp entfernt.',
   'f1.h': 'Acht Sprachen', 'f1.p': 'Englisch, Arabisch, Niederländisch, Deutsch, Polnisch, Tschechisch, Französisch und Russisch, mit Rechts-nach-links-Layout für Arabisch.',
   'f2.h': 'Live-Öffnungsstatus', 'f2.p': 'Jedes Restaurant und jede Bar zeigt „Geöffnet“ oder „Geschlossen“ nach der aktuellen Uhrzeit, jede Minute aktualisiert.',
   'f3.h': 'Abendprogramm', 'f3.p': 'Eine Karte für jeden Abend der Woche, damit Gäste ihren Aufenthalt um die Shows planen können.',
   'f4.h': 'Restaurantführer', 'f4.p': 'Restaurants und Bars in zwei Tabs, mit Küche, Lage und Essenszeiten.',
   'f5.h': 'Zum Home-Bildschirm', 'f5.p': 'Wird direkt aus dem Browser wie eine App installiert. Kein App Store nötig.',
   'f6.h': 'WhatsApp-Kontakt', 'f6.p': 'Ein schwebender Button und eine Kontaktkarte für Fragen und Wünsche.',
   'n1': 'Sprachen', 'n2': 'Restaurants', 'n3': 'Bars', 'n4': 'Abendshows pro Woche',
   'c1': 'Nacht', 'c2': 'Signaturrot', 'c3': 'Tiefrot',
  },
  'it': {
   'type': 'Web app per gli ospiti del resort',
   'lede': 'Una web app per gli ospiti di un resort cinque stelle con acquapark a Marsa Alam: ristoranti, attività e programma serale in otto lingue.',
   'client': 'Amarina Jannah Resort &amp; Aqua Park', 'where': 'Marsa Alam, Mar Rosso',
   'brief': 'Gli ospiti arrivano da tutta Europa e hanno bisogno di un unico posto sul telefono per ristoranti, orari, attività e lo show della sera, nella loro lingua e senza scaricare app.',
   'built': 'Una web app veloce che si installa dal browser. Ogni ristorante e bar mostra se è aperto in questo momento, il programma serale ha una scheda per ogni sera e la galleria usa le vere foto del resort. WhatsApp è a un tocco da ogni schermata.',
   'f1.h': 'Otto lingue', 'f1.p': 'Inglese, arabo, olandese, tedesco, polacco, ceco, francese e russo, con layout da destra a sinistra per l’arabo.',
   'f2.h': 'Aperto o chiuso, live', 'f2.p': 'Ogni ristorante e bar mostra Aperto o Chiuso in base all’ora attuale, aggiornato ogni minuto.',
   'f3.h': 'Programma serale', 'f3.p': 'Una scheda per ogni sera della settimana, così gli ospiti organizzano il soggiorno intorno agli show.',
   'f4.h': 'Guida ai ristoranti', 'f4.p': 'Ristoranti e bar in due schede, con cucina, posizione e orari dei pasti.',
   'f5.h': 'Sulla schermata Home', 'f5.p': 'Si installa come un’app direttamente dal browser. Nessun app store.',
   'f6.h': 'Contatto WhatsApp', 'f6.p': 'Un pulsante fluttuante e una scheda contatti per domande e richieste.',
   'n1': 'Lingue', 'n2': 'Ristoranti', 'n3': 'Bar', 'n4': 'Show serali a settimana',
   'c1': 'Notte', 'c2': 'Rosso firma', 'c3': 'Rosso scuro',
  },
 },
 {
  'slug': 'joy-boy', 'shot': 'joyboy', 'name': 'Joy Boy Agency', 'acc': '#FF4D2E', 'pick': 'brand',
  'url': 'https://seifabas33-pixel.github.io/joyBoy-agency/', 'urlLabel': 'joyBoy-agency',
  'langs': 'EN · DE · IT',
  'nums': ['3', '5', '6', '7/7'],
  'swatches': [('#0D0A14', 'c1'), ('#FF4D2E', 'c2'), ('#FFD60A', 'c3'), ('#D63BC6', 'c4')],
  'fonts': ['Bricolage Grotesque', 'Instrument Sans', 'IBM Plex Mono'],
  'tech': ['HTML', 'CSS', 'JavaScript', 'Firebase', 'Google Apps Script', 'GitHub Pages'],
  'en': {
   'type': 'Entertainment agency website',
   'lede': 'The website for my own entertainment agency, built to win resort contracts, with show reels, awards and a staff portal behind it.',
   'client': 'Joy Boy Agency (co-founder)', 'where': 'Marsa Alam · Hurghada · Sahl Hasheesh',
   'brief': 'Resort managers decide fast. Joy Boy needed a site that shows the team on stage, proves results with awards and guest reviews, and makes it easy to start a conversation.',
   'built': 'A bold, playful portfolio in English, German and Italian, with a spotlight photo wall, show reels, awards, guest quotes and an FAQ. Behind it is a private staff portal for shift check-in, rosters and guest feedback.',
   'f1.h': 'Spotlight hero', 'f1.p': 'A drifting wall of show photos lit by a spotlight that follows your finger or cursor.',
   'f2.h': 'Show reels', 'f2.p': 'Five reels from real programme nights: fire, Echo of Egypt, kids, light show and theme nights.',
   'f3.h': 'Awards &amp; reviews', 'f3.p': 'Booking.com and HolidayCheck awards next to real guest quotes.',
   'f4.h': 'Three languages', 'f4.p': 'English, German and Italian pages, each with its own address for Google.',
   'f5.h': 'Staff portal', 'f5.p': 'Google sign-in, location-checked shift check-in, rosters and payroll for the team.',
   'f6.h': 'Guest feedback by QR', 'f6.p': 'QR cards lead guests to a feedback page that syncs to Google Sheets.',
   'n1': 'Languages', 'n2': 'Show reels', 'n3': 'Award cards', 'n4': 'Nights a week',
   'c1': 'Aubergine', 'c2': 'Coral', 'c3': 'Yellow', 'c4': 'Magenta',
  },
  'ar': {
   'type': 'موقع وكالة ترفيه',
   'lede': 'موقع وكالة الترفيه التي شاركت في تأسيسها، مصمَّم للفوز بعقود المنتجعات، مع فيديوهات العروض والجوائز وبوابة للفريق.',
   'client': 'وكالة جوي بوي (شريك مؤسس)', 'where': 'مرسى علم · الغردقة · سهل حشيش',
   'brief': 'مديرو المنتجعات يقررون بسرعة. احتاجت جوي بوي موقعًا يُظهر الفريق على المسرح، ويثبت النتائج بالجوائز وآراء الضيوف، ويسهّل بدء المحادثة.',
   'built': 'موقع جريء ومرح بالإنجليزية والألمانية والإيطالية، فيه جدار صور تحت ضوء كشّاف، وفيديوهات العروض، والجوائز، وآراء الضيوف، وأسئلة شائعة. وخلفه بوابة خاصة للفريق لتسجيل الحضور والجداول وآراء الضيوف.',
   'f1.h': 'واجهة الضوء الكشّاف', 'f1.p': 'جدار متحرك من صور العروض يضيئه ضوء يتبع إصبعك أو مؤشر الفأرة.',
   'f2.h': 'فيديوهات العروض', 'f2.p': 'خمسة فيديوهات من ليالٍ حقيقية: النار، صدى مصر، الأطفال، عرض الإضاءة والليالي المميزة.',
   'f3.h': 'الجوائز والتقييمات', 'f3.p': 'جوائز Booking.com وHolidayCheck بجانب آراء حقيقية من الضيوف.',
   'f4.h': 'ثلاث لغات', 'f4.p': 'صفحات بالإنجليزية والألمانية والإيطالية، لكل منها رابط خاص لجوجل.',
   'f5.h': 'بوابة الفريق', 'f5.p': 'دخول بحساب جوجل، وتسجيل حضور مرتبط بالموقع، وجداول ورواتب للفريق.',
   'f6.h': 'آراء الضيوف عبر QR', 'f6.p': 'بطاقات QR تقود الضيوف لصفحة تقييم تُحفظ في Google Sheets.',
   'n1': 'لغات', 'n2': 'فيديوهات عروض', 'n3': 'بطاقات جوائز', 'n4': 'ليالٍ في الأسبوع',
   'c1': 'باذنجاني', 'c2': 'مرجاني', 'c3': 'أصفر', 'c4': 'أرجواني',
  },
  'de': {
   'type': 'Website einer Entertainment-Agentur',
   'lede': 'Die Website meiner eigenen Entertainment-Agentur, gebaut, um Resort-Verträge zu gewinnen, mit Show-Reels, Auszeichnungen und einem Mitarbeiterportal dahinter.',
   'client': 'Joy Boy Agency (Mitgründer)', 'where': 'Marsa Alam · Hurghada · Sahl Hasheesh',
   'brief': 'Resortmanager entscheiden schnell. Joy Boy brauchte eine Seite, die das Team auf der Bühne zeigt, Ergebnisse mit Auszeichnungen und Gästebewertungen belegt und den ersten Kontakt leicht macht.',
   'built': 'Ein mutiges, verspieltes Portfolio auf Englisch, Deutsch und Italienisch, mit Spotlight-Fotowand, Show-Reels, Auszeichnungen, Gästestimmen und FAQ. Dahinter liegt ein privates Mitarbeiterportal für Schicht-Check-in, Dienstpläne und Gästefeedback.',
   'f1.h': 'Spotlight-Hero', 'f1.p': 'Eine treibende Wand aus Showfotos, beleuchtet von einem Spot, der Finger oder Cursor folgt.',
   'f2.h': 'Show-Reels', 'f2.p': 'Fünf Reels von echten Programmabenden: Feuer, Echo of Egypt, Kids, Lichtshow und Themenabende.',
   'f3.h': 'Auszeichnungen &amp; Bewertungen', 'f3.p': 'Booking.com- und HolidayCheck-Auszeichnungen neben echten Gästestimmen.',
   'f4.h': 'Drei Sprachen', 'f4.p': 'Englische, deutsche und italienische Seiten, jede mit eigener Adresse für Google.',
   'f5.h': 'Mitarbeiterportal', 'f5.p': 'Google-Anmeldung, standortgeprüfter Schicht-Check-in, Dienstpläne und Gehaltsabrechnung.',
   'f6.h': 'Gästefeedback per QR', 'f6.p': 'QR-Karten führen Gäste zu einer Feedbackseite, die mit Google Sheets synchronisiert.',
   'n1': 'Sprachen', 'n2': 'Show-Reels', 'n3': 'Auszeichnungen', 'n4': 'Abende pro Woche',
   'c1': 'Aubergine', 'c2': 'Koralle', 'c3': 'Gelb', 'c4': 'Magenta',
  },
  'it': {
   'type': 'Sito di un’agenzia di animazione',
   'lede': 'Il sito della mia agenzia di animazione, pensato per vincere contratti con i resort, con video degli show, premi e un portale per lo staff.',
   'client': 'Joy Boy Agency (co-fondatore)', 'where': 'Marsa Alam · Hurghada · Sahl Hasheesh',
   'brief': 'I manager dei resort decidono in fretta. Joy Boy aveva bisogno di un sito che mostrasse la squadra sul palco, provasse i risultati con premi e recensioni e rendesse facile iniziare a parlare.',
   'built': 'Un portfolio audace e giocoso in inglese, tedesco e italiano, con un muro di foto sotto un riflettore, video degli show, premi, recensioni e FAQ. Dietro c’è un portale privato per lo staff: check-in dei turni, turni e feedback degli ospiti.',
   'f1.h': 'Hero con riflettore', 'f1.p': 'Un muro di foto degli show che scorre, illuminato da un riflettore che segue il dito o il cursore.',
   'f2.h': 'Video degli show', 'f2.p': 'Cinque video da vere serate: fuoco, Echo of Egypt, bambini, light show e serate a tema.',
   'f3.h': 'Premi e recensioni', 'f3.p': 'I premi Booking.com e HolidayCheck accanto a vere parole degli ospiti.',
   'f4.h': 'Tre lingue', 'f4.p': 'Pagine in inglese, tedesco e italiano, ognuna con il suo indirizzo per Google.',
   'f5.h': 'Portale dello staff', 'f5.p': 'Accesso con Google, check-in dei turni con verifica della posizione, turni e buste paga.',
   'f6.h': 'Feedback con QR', 'f6.p': 'Card QR portano gli ospiti a una pagina di feedback sincronizzata con Google Sheets.',
   'n1': 'Lingue', 'n2': 'Video degli show', 'n3': 'Premi', 'n4': 'Sere a settimana',
   'c1': 'Melanzana', 'c2': 'Corallo', 'c3': 'Giallo', 'c4': 'Magenta',
  },
 },
 {
  'slug': 'soho-bar', 'shot': 'soho', 'name': 'Soho Bar', 'acc': '#D4A24C', 'pick': 'web',
  'url': 'https://soho-bar.com', 'urlLabel': 'soho-bar.com',
  'langs': 'EN · DE · IT',
  'nums': ['5.0', '4.9', '3', '5'],
  'swatches': [('#0D0B09', 'c1'), ('#D4A24C', 'c2'), ('#F5EAD8', 'c3')],
  'fonts': ['Playfair Display', 'Inter'],
  'tech': ['HTML', 'CSS', 'JavaScript', 'Structured data', 'Google Maps'],
  'en': {
   'type': 'Restaurant &amp; bar website',
   'lede': 'A website for a tapas and grill bar on the Port Ghalib marina, with the menu, reviews and table booking straight to WhatsApp.',
   'client': 'Soho Bar · Tapas &amp; Grill', 'where': 'Port Ghalib Marina, Marsa Alam',
   'brief': 'Soho Bar is rated number one in Port Ghalib, but tourists in nearby hotels had no easy way to see the menu, learn about the free hotel pick-up or book a table.',
   'built': 'A warm dark-and-gold site in three languages: the menu in five tabs, ratings from TripAdvisor and Google on the first screen, a map, and a booking form that turns into a ready-written WhatsApp message.',
   'f1.h': 'Booking by WhatsApp', 'f1.p': 'Name, date, time, guests and hotel for the free pick-up, sent as one ready-made WhatsApp message.',
   'f2.h': 'Menu in five tabs', 'f2.p': 'Grill, tapas, Italian pizzas, vegan, and bar &amp; cocktails.',
   'f3.h': 'Three languages', 'f3.p': 'English, German and Italian, chosen automatically from the visitor’s phone.',
   'f4.h': 'Ratings up front', 'f4.p': 'TripAdvisor, Google and Restaurant Guru scores on the first screen.',
   'f5.h': 'Find us', 'f5.p': 'A built-in map and the opening hours, every day 10:30 to midnight.',
   'f6.h': 'Ready for Google', 'f6.p': 'Restaurant details are marked up so search results can show hours and prices.',
   'n1': 'TripAdvisor rating', 'n2': 'Google rating', 'n3': 'Languages', 'n4': 'Menu sections',
   'c1': 'Espresso', 'c2': 'Gold', 'c3': 'Cream',
  },
  'ar': {
   'type': 'موقع مطعم وبار',
   'lede': 'موقع لمطعم وبار تاباس ومشويات على مارينا بورت غالب، فيه المنيو والتقييمات وحجز الطاولة مباشرة عبر واتساب.',
   'client': 'سوهو بار · تاباس ومشويات', 'where': 'مارينا بورت غالب، مرسى علم',
   'brief': 'سوهو بار هو الأعلى تقييمًا في بورت غالب، لكن السياح في الفنادق القريبة لم تكن لديهم طريقة سهلة لرؤية المنيو أو معرفة خدمة التوصيل المجاني من الفندق أو حجز طاولة.',
   'built': 'موقع دافئ بالأسود والذهبي بثلاث لغات: المنيو في خمسة تبويبات، وتقييمات TripAdvisor وجوجل في الشاشة الأولى، وخريطة، ونموذج حجز يتحول إلى رسالة واتساب جاهزة.',
   'f1.h': 'الحجز عبر واتساب', 'f1.p': 'الاسم والتاريخ والوقت وعدد الضيوف والفندق للتوصيل المجاني، في رسالة واتساب واحدة جاهزة.',
   'f2.h': 'منيو في خمسة تبويبات', 'f2.p': 'المشويات، التاباس، البيتزا الإيطالية، النباتي، والبار والكوكتيلات.',
   'f3.h': 'ثلاث لغات', 'f3.p': 'الإنجليزية والألمانية والإيطالية، تُختار تلقائيًا من هاتف الزائر.',
   'f4.h': 'التقييمات أولًا', 'f4.p': 'تقييمات TripAdvisor وجوجل وRestaurant Guru في الشاشة الأولى.',
   'f5.h': 'موقعنا', 'f5.p': 'خريطة مدمجة ومواعيد العمل، يوميًا من 10:30 حتى منتصف الليل.',
   'f6.h': 'جاهز لجوجل', 'f6.p': 'بيانات المطعم مُعلَّمة لتظهر المواعيد والأسعار في نتائج البحث.',
   'n1': 'تقييم TripAdvisor', 'n2': 'تقييم جوجل', 'n3': 'لغات', 'n4': 'أقسام المنيو',
   'c1': 'إسبريسو', 'c2': 'ذهبي', 'c3': 'كريمي',
  },
  'de': {
   'type': 'Website für Restaurant &amp; Bar',
   'lede': 'Eine Website für eine Tapas- und Grillbar an der Marina von Port Ghalib, mit Speisekarte, Bewertungen und Tischreservierung direkt per WhatsApp.',
   'client': 'Soho Bar · Tapas &amp; Grill', 'where': 'Port Ghalib Marina, Marsa Alam',
   'brief': 'Die Soho Bar ist die Nummer eins in Port Ghalib, aber Touristen in den Hotels nebenan konnten die Karte, den kostenlosen Hotel-Abholservice oder eine Reservierung nicht leicht finden.',
   'built': 'Eine warme Seite in Dunkel und Gold in drei Sprachen: die Karte in fünf Tabs, Bewertungen von TripAdvisor und Google auf dem ersten Bildschirm, eine Karte und ein Reservierungsformular, das zur fertigen WhatsApp-Nachricht wird.',
   'f1.h': 'Reservierung per WhatsApp', 'f1.p': 'Name, Datum, Uhrzeit, Personen und Hotel für die kostenlose Abholung, als fertige WhatsApp-Nachricht.',
   'f2.h': 'Karte in fünf Tabs', 'f2.p': 'Grill, Tapas, italienische Pizza, vegan sowie Bar &amp; Cocktails.',
   'f3.h': 'Drei Sprachen', 'f3.p': 'Englisch, Deutsch und Italienisch, automatisch passend zum Handy des Besuchers.',
   'f4.h': 'Bewertungen zuerst', 'f4.p': 'TripAdvisor-, Google- und Restaurant-Guru-Werte auf dem ersten Bildschirm.',
   'f5.h': 'So finden Sie uns', 'f5.p': 'Eingebaute Karte und Öffnungszeiten, täglich 10:30 bis Mitternacht.',
   'f6.h': 'Bereit für Google', 'f6.p': 'Restaurantdaten sind so ausgezeichnet, dass Suchergebnisse Zeiten und Preise zeigen können.',
   'n1': 'TripAdvisor-Bewertung', 'n2': 'Google-Bewertung', 'n3': 'Sprachen', 'n4': 'Kartenbereiche',
   'c1': 'Espresso', 'c2': 'Gold', 'c3': 'Creme',
  },
  'it': {
   'type': 'Sito per ristorante e bar',
   'lede': 'Un sito per un bar di tapas e grill sulla marina di Port Ghalib, con menu, recensioni e prenotazione del tavolo direttamente su WhatsApp.',
   'client': 'Soho Bar · Tapas &amp; Grill', 'where': 'Marina di Port Ghalib, Marsa Alam',
   'brief': 'Il Soho Bar è il numero uno a Port Ghalib, ma i turisti negli hotel vicini non avevano un modo semplice per vedere il menu, scoprire il transfer gratuito dall’hotel o prenotare un tavolo.',
   'built': 'Un sito caldo, scuro e oro, in tre lingue: il menu in cinque schede, i voti di TripAdvisor e Google nella prima schermata, una mappa e un modulo di prenotazione che diventa un messaggio WhatsApp già scritto.',
   'f1.h': 'Prenotazione su WhatsApp', 'f1.p': 'Nome, data, ora, persone e hotel per il transfer gratuito, in un unico messaggio WhatsApp pronto.',
   'f2.h': 'Menu in cinque schede', 'f2.p': 'Grill, tapas, pizze italiane, vegano, e bar e cocktail.',
   'f3.h': 'Tre lingue', 'f3.p': 'Inglese, tedesco e italiano, scelti in automatico dal telefono del visitatore.',
   'f4.h': 'Recensioni in primo piano', 'f4.p': 'I voti di TripAdvisor, Google e Restaurant Guru nella prima schermata.',
   'f5.h': 'Dove siamo', 'f5.p': 'Mappa integrata e orari, ogni giorno dalle 10:30 a mezzanotte.',
   'f6.h': 'Pronto per Google', 'f6.p': 'I dati del ristorante sono marcati perché i risultati di ricerca mostrino orari e prezzi.',
   'n1': 'Voto TripAdvisor', 'n2': 'Voto Google', 'n3': 'Lingue', 'n4': 'Sezioni del menu',
   'c1': 'Espresso', 'c2': 'Oro', 'c3': 'Crema',
  },
 },
 {
  'slug': 'old-palace', 'shot': 'oldpalace', 'name': 'Old Palace Resort', 'acc': '#C9A84C', 'pick': 'web',
  'url': 'https://splash-entertainment-git-claude-ecstatic-cerf-4qwkt-splash2.vercel.app', 'urlLabel': 'old-palace · guest app',
  'langs': 'EN · AR · DE · RU',
  'nums': ['9', '7', '14', '4'],
  'swatches': [('#06060F', 'c1'), ('#C9A84C', 'c2'), ('#F0EBE0', 'c3')],
  'fonts': ['Cormorant Garamond', 'Raleway', 'Tajawal'],
  'tech': ['HTML', 'CSS', 'JavaScript', 'Service worker', 'Open-Meteo', 'JSON'],
  'en': {
   'type': 'Guest entertainment platform',
   'lede': 'A guest platform for Old Palace Resort with the daily programme, concierge, excursions and feedback. It works offline.',
   'client': 'Old Palace Resort', 'where': 'Sahl Hasheesh, Hurghada',
   'brief': 'Guests needed one place to see what’s on today, book excursions, ask for room services and tell management how their stay is going, in their own language and without installing anything.',
   'built': 'An installable web app that keeps working without Wi-Fi. It has a 7-day programme with a live “Happening now” card, a personal “My Day” with reminders, a WhatsApp concierge, live weather, and staff tools to update the programme.',
   'f1.h': 'Happening now', 'f1.p': 'Live countdowns to the next activity and tonight’s show, updated every minute.',
   'f2.h': 'My Day', 'f2.p': 'Guests star activities and get a reminder 15 minutes before each one starts.',
   'f3.h': 'WhatsApp concierge', 'f3.p': '14 one-tap requests with the room number already filled in.',
   'f4.h': 'Works offline', 'f4.p': 'Installs to the home screen and keeps working without Wi-Fi.',
   'f5.h': 'Four languages', 'f5.p': 'English, Arabic, German and Russian, with a right-to-left layout for Arabic.',
   'f6.h': 'Staff tools', 'f6.p': 'A staff sign-in with a printable programme, plus an editor for the programme, Wi-Fi details and excursions.',
   'n1': 'Guest screens', 'n2': 'Restaurants &amp; bars', 'n3': 'Concierge requests', 'n4': 'Languages',
   'c1': 'Ink', 'c2': 'Palace gold', 'c3': 'Ivory',
  },
  'ar': {
   'type': 'منصة ترفيه للضيوف',
   'lede': 'منصة لضيوف أولد بالاس ريزورت فيها البرنامج اليومي والكونسيرج والرحلات والتقييمات، وتعمل حتى بدون إنترنت.',
   'client': 'أولد بالاس ريزورت', 'where': 'سهل حشيش، الغردقة',
   'brief': 'احتاج الضيوف مكانًا واحدًا لمعرفة فعاليات اليوم وحجز الرحلات وطلب خدمات الغرفة وإخبار الإدارة برأيهم في إقامتهم، بلغتهم ومن دون تثبيت أي شيء.',
   'built': 'تطبيق ويب قابل للتثبيت يعمل بدون واي فاي. فيه برنامج لسبعة أيام مع بطاقة «يحدث الآن» مباشرة، و«يومي» الشخصي مع تذكيرات، وكونسيرج عبر واتساب، وطقس مباشر، وأدوات للفريق لتحديث البرنامج.',
   'f1.h': 'يحدث الآن', 'f1.p': 'عدّ تنازلي مباشر للنشاط التالي وعرض الليلة، يتحدّث كل دقيقة.',
   'f2.h': 'يومي', 'f2.p': 'يختار الضيوف أنشطتهم ويصلهم تذكير قبل بدء كل نشاط بـ15 دقيقة.',
   'f3.h': 'كونسيرج واتساب', 'f3.p': '14 طلبًا بلمسة واحدة مع رقم الغرفة جاهزًا.',
   'f4.h': 'يعمل بدون إنترنت', 'f4.p': 'يُثبَّت على الشاشة الرئيسية ويستمر في العمل بدون واي فاي.',
   'f5.h': 'أربع لغات', 'f5.p': 'الإنجليزية والعربية والألمانية والروسية، مع اتجاه من اليمين لليسار للعربية.',
   'f6.h': 'أدوات الفريق', 'f6.p': 'دخول للفريق مع برنامج قابل للطباعة، ومحرر للبرنامج وبيانات الواي فاي والرحلات.',
   'n1': 'شاشات للضيوف', 'n2': 'مطاعم وبارات', 'n3': 'طلبات كونسيرج', 'n4': 'لغات',
   'c1': 'حبر', 'c2': 'ذهبي القصر', 'c3': 'عاجي',
  },
  'de': {
   'type': 'Entertainment-Plattform für Gäste',
   'lede': 'Eine Gästeplattform für das Old Palace Resort mit Tagesprogramm, Concierge, Ausflügen und Feedback. Sie funktioniert auch offline.',
   'client': 'Old Palace Resort', 'where': 'Sahl Hasheesh, Hurghada',
   'brief': 'Gäste brauchten einen Ort, um zu sehen, was heute läuft, Ausflüge zu buchen, Zimmerservice anzufragen und dem Management Feedback zu geben, in ihrer Sprache und ohne etwas zu installieren.',
   'built': 'Eine installierbare Web-App, die auch ohne WLAN funktioniert. Sie hat ein 7-Tage-Programm mit einer Live-Karte „Gerade jetzt“, einen persönlichen „Mein Tag“ mit Erinnerungen, einen WhatsApp-Concierge, Live-Wetter und Werkzeuge fürs Team, um das Programm zu pflegen.',
   'f1.h': 'Gerade jetzt', 'f1.p': 'Live-Countdowns bis zur nächsten Aktivität und zur Abendshow, jede Minute aktualisiert.',
   'f2.h': 'Mein Tag', 'f2.p': 'Gäste markieren Aktivitäten und werden 15 Minuten vor Beginn erinnert.',
   'f3.h': 'WhatsApp-Concierge', 'f3.p': '14 Anfragen per Tipp, die Zimmernummer ist schon ausgefüllt.',
   'f4.h': 'Funktioniert offline', 'f4.p': 'Lässt sich auf den Home-Bildschirm legen und läuft auch ohne WLAN.',
   'f5.h': 'Vier Sprachen', 'f5.p': 'Englisch, Arabisch, Deutsch und Russisch, mit Rechts-nach-links-Layout für Arabisch.',
   'f6.h': 'Werkzeuge fürs Team', 'f6.p': 'Ein Mitarbeiter-Login mit druckbarem Programm sowie ein Editor für Programm, WLAN-Daten und Ausflüge.',
   'n1': 'Gäste-Bildschirme', 'n2': 'Restaurants &amp; Bars', 'n3': 'Concierge-Anfragen', 'n4': 'Sprachen',
   'c1': 'Tinte', 'c2': 'Palastgold', 'c3': 'Elfenbein',
  },
  'it': {
   'type': 'Piattaforma di intrattenimento per gli ospiti',
   'lede': 'Una piattaforma per gli ospiti dell’Old Palace Resort con programma giornaliero, concierge, escursioni e feedback. Funziona anche offline.',
   'client': 'Old Palace Resort', 'where': 'Sahl Hasheesh, Hurghada',
   'brief': 'Gli ospiti avevano bisogno di un unico posto per vedere cosa c’è oggi, prenotare escursioni, chiedere servizi in camera e dire alla direzione come va il soggiorno, nella loro lingua e senza installare nulla.',
   'built': 'Una web app installabile che funziona anche senza Wi-Fi. Ha un programma di 7 giorni con una scheda live “In corso”, un “La mia giornata” personale con promemoria, un concierge su WhatsApp, il meteo live e strumenti per lo staff per aggiornare il programma.',
   'f1.h': 'In corso', 'f1.p': 'Conto alla rovescia live per la prossima attività e lo show della sera, aggiornato ogni minuto.',
   'f2.h': 'La mia giornata', 'f2.p': 'Gli ospiti segnano le attività e ricevono un promemoria 15 minuti prima dell’inizio.',
   'f3.h': 'Concierge su WhatsApp', 'f3.p': '14 richieste con un tocco, con il numero di camera già inserito.',
   'f4.h': 'Funziona offline', 'f4.p': 'Si installa sulla schermata Home e funziona anche senza Wi-Fi.',
   'f5.h': 'Quattro lingue', 'f5.p': 'Inglese, arabo, tedesco e russo, con layout da destra a sinistra per l’arabo.',
   'f6.h': 'Strumenti per lo staff', 'f6.p': 'Un accesso per lo staff con programma stampabile, più un editor per programma, Wi-Fi ed escursioni.',
   'n1': 'Schermate per gli ospiti', 'n2': 'Ristoranti e bar', 'n3': 'Richieste al concierge', 'n4': 'Lingue',
   'c1': 'Inchiostro', 'c2': 'Oro del palazzo', 'c3': 'Avorio',
  },
 },
 {
  'slug': 'hanna', 'shot': 'hanna', 'name': 'Hanna · Homes Bay', 'acc': '#B4283A', 'pick': 'brand',
  'url': '/hanna.html', 'urlLabel': 'seifabas.vercel.app/hanna',
  'langs': 'EN · PL',
  'nums': ['12', '4', '4', '2'],
  'swatches': [('#61141C', 'c1'), ('#F2EEEB', 'c2')],
  'fonts': ['Montserrat'],
  'tech': ['HTML', 'CSS', 'JavaScript', 'Web app manifest'],
  'en': {
   'type': 'Real-estate agent website',
   'lede': 'A personal website for a Polish-speaking real-estate agent in Hurghada, with verified listings, a clear process and WhatsApp contact.',
   'client': 'Hanna Różczka · Homes Bay', 'where': 'Hurghada, Red Sea',
   'brief': 'Hanna helps international buyers, many of them from Poland, buy property on the Red Sea. Buyers needed to trust her before the first call.',
   'built': 'A light, glassy site in English and Polish with twelve verified listings, her four-step verification process, client testimonials and a contact form that writes the WhatsApp message for the buyer. It comes with a matching digital business card.',
   'f1.h': 'English &amp; Polish', 'f1.p': 'A full translation, including the animated headline.',
   'f2.h': 'Verified listings', 'f2.p': '12 properties across 4 developments, each with size, bedrooms and view.',
   'f3.h': 'Verification process', 'f3.p': 'The four checks every property passes before Hanna shows it to a buyer.',
   'f4.h': 'WhatsApp or email', 'f4.p': 'One form, two buttons. Each one writes the message for the buyer.',
   'f5.h': 'Digital business card', 'f5.p': 'A separate card page she can share in one tap.',
   'f6.h': 'Motion', 'f6.p': 'Particles, a typewriter headline, 3D tilt cards and count-up numbers.',
   'n1': 'Listings', 'n2': 'Developments', 'n3': 'Verification steps', 'n4': 'Languages',
   'c1': 'Crimson', 'c2': 'Warm cream',
  },
  'ar': {
   'type': 'موقع وسيطة عقارية',
   'lede': 'موقع شخصي لوسيطة عقارية تتحدث البولندية في الغردقة، فيه عقارات موثّقة وخطوات واضحة وتواصل عبر واتساب.',
   'client': 'هانا روجتشكا · Homes Bay', 'where': 'الغردقة، البحر الأحمر',
   'brief': 'تساعد هانا المشترين الأجانب، وكثير منهم من بولندا، على شراء عقارات على البحر الأحمر. كان على المشترين أن يثقوا بها قبل أول مكالمة.',
   'built': 'موقع فاتح بطابع زجاجي بالإنجليزية والبولندية، فيه اثنا عشر عقارًا موثّقًا، وخطوات التحقق الأربع، وآراء العملاء، ونموذج تواصل يكتب رسالة واتساب بدلًا من المشتري. ومعه بطاقة عمل رقمية بنفس التصميم.',
   'f1.h': 'الإنجليزية والبولندية', 'f1.p': 'ترجمة كاملة حتى العنوان المتحرك.',
   'f2.h': 'عقارات موثّقة', 'f2.p': '12 عقارًا في 4 مشروعات، لكل منها المساحة والغرف والإطلالة.',
   'f3.h': 'خطوات التحقق', 'f3.p': 'الفحوصات الأربعة التي يجتازها كل عقار قبل أن تعرضه هانا على المشتري.',
   'f4.h': 'واتساب أو بريد', 'f4.p': 'نموذج واحد وزرّان، كلٌّ منهما يكتب الرسالة للمشتري.',
   'f5.h': 'بطاقة عمل رقمية', 'f5.p': 'صفحة بطاقة مستقلة تشاركها بلمسة.',
   'f6.h': 'الحركة', 'f6.p': 'جزيئات متحركة، وعنوان يُكتب حرفًا حرفًا، وبطاقات مائلة ثلاثية الأبعاد، وأرقام تعدّ تصاعديًا.',
   'n1': 'عقارات', 'n2': 'مشروعات', 'n3': 'خطوات تحقق', 'n4': 'لغتان',
   'c1': 'قرمزي', 'c2': 'كريمي دافئ',
  },
  'de': {
   'type': 'Website einer Immobilienmaklerin',
   'lede': 'Eine persönliche Website für eine polnischsprachige Immobilienmaklerin in Hurghada, mit geprüften Angeboten, klarem Ablauf und WhatsApp-Kontakt.',
   'client': 'Hanna Różczka · Homes Bay', 'where': 'Hurghada, Rotes Meer',
   'brief': 'Hanna hilft internationalen Käufern, viele davon aus Polen, beim Immobilienkauf am Roten Meer. Käufer sollten ihr schon vor dem ersten Anruf vertrauen.',
   'built': 'Eine helle Seite im Glas-Look auf Englisch und Polnisch mit zwölf geprüften Angeboten, ihrem vierstufigen Prüfprozess, Kundenstimmen und einem Kontaktformular, das die WhatsApp-Nachricht für den Käufer schreibt. Dazu gibt es eine passende digitale Visitenkarte.',
   'f1.h': 'Englisch &amp; Polnisch', 'f1.p': 'Vollständig übersetzt, auch die animierte Überschrift.',
   'f2.h': 'Geprüfte Angebote', 'f2.p': '12 Immobilien in 4 Projekten, jeweils mit Größe, Schlafzimmern und Aussicht.',
   'f3.h': 'Prüfprozess', 'f3.p': 'Die vier Prüfungen, die jede Immobilie besteht, bevor Hanna sie zeigt.',
   'f4.h': 'WhatsApp oder E-Mail', 'f4.p': 'Ein Formular, zwei Buttons. Beide schreiben die Nachricht für den Käufer.',
   'f5.h': 'Digitale Visitenkarte', 'f5.p': 'Eine eigene Kartenseite, die sie mit einem Tipp teilen kann.',
   'f6.h': 'Bewegung', 'f6.p': 'Partikel, Schreibmaschinen-Überschrift, 3D-Kippkarten und hochzählende Zahlen.',
   'n1': 'Angebote', 'n2': 'Projekte', 'n3': 'Prüfschritte', 'n4': 'Sprachen',
   'c1': 'Karmesin', 'c2': 'Warmes Creme',
  },
  'it': {
   'type': 'Sito per un’agente immobiliare',
   'lede': 'Un sito personale per un’agente immobiliare di lingua polacca a Hurghada, con immobili verificati, un processo chiaro e contatto su WhatsApp.',
   'client': 'Hanna Różczka · Homes Bay', 'where': 'Hurghada, Mar Rosso',
   'brief': 'Hanna aiuta acquirenti internazionali, molti dalla Polonia, a comprare casa sul Mar Rosso. Gli acquirenti dovevano fidarsi di lei prima della prima chiamata.',
   'built': 'Un sito chiaro, effetto vetro, in inglese e polacco, con dodici immobili verificati, il suo processo di verifica in quattro passi, le recensioni dei clienti e un modulo che scrive il messaggio WhatsApp per l’acquirente. In più, un biglietto da visita digitale coordinato.',
   'f1.h': 'Inglese e polacco', 'f1.p': 'Traduzione completa, anche del titolo animato.',
   'f2.h': 'Immobili verificati', 'f2.p': '12 immobili in 4 complessi, ognuno con metratura, camere e vista.',
   'f3.h': 'Processo di verifica', 'f3.p': 'I quattro controlli che ogni immobile supera prima che Hanna lo mostri.',
   'f4.h': 'WhatsApp o email', 'f4.p': 'Un modulo, due pulsanti. Ognuno scrive il messaggio per l’acquirente.',
   'f5.h': 'Biglietto da visita digitale', 'f5.p': 'Una pagina biglietto separata da condividere con un tocco.',
   'f6.h': 'Movimento', 'f6.p': 'Particelle, titolo a macchina da scrivere, card inclinabili in 3D e numeri che contano.',
   'n1': 'Immobili', 'n2': 'Complessi', 'n3': 'Passi di verifica', 'n4': 'Lingue',
   'c1': 'Cremisi', 'c2': 'Crema calda',
  },
 },
 {
  'slug': 'larimar', 'shot': 'larimar', 'name': 'Larimar', 'acc': '#05A8C1', 'pick': 'brand',
  'url': 'https://seifabas33-pixel.github.io/claude-/agent2.html?v=2', 'urlLabel': 'larimar · agent',
  'langs': 'EN',
  'nums': ['3', '65', '105+', '18km'],
  'swatches': [('#025B88', 'c1'), ('#05A8C1', 'c2'), ('#DB5E2B', 'c3'), ('#F8F6F3', 'c4')],
  'fonts': ['Playfair Display', 'Inter'],
  'tech': ['HTML', 'CSS', 'JavaScript'],
  'en': {
   'type': 'Sales agent portfolio',
   'lede': 'A personal portfolio for a property sales supervisor at Larimar, Port Ghalib, covering the projects, the lifestyle and the reasons to invest.',
   'client': 'Mohamed Sharawi · Larimar', 'where': 'Port Ghalib, Marsa Alam',
   'brief': 'Mohamed sells villas and suites at Larimar to buyers abroad. He needed one link he can send to every lead that explains the projects and makes it easy to ask for prices.',
   'built': 'A clean navy-and-teal portfolio with three project cards, life at Port Ghalib, five reasons to invest, and a contact form that sends a WhatsApp message with the chosen project.',
   'f1.h': 'Project cards', 'f1.p': 'Villas, Suites and Larimar 3, each with unit sizes and a “Request pricing” button.',
   'f2.h': 'WhatsApp enquiries', 'f2.p': 'Pick a project and the form writes the WhatsApp message.',
   'f3.h': 'Why invest', 'f3.p': 'Five clear reasons, from turnkey delivery and rental demand to hotel management and payment plans.',
   'f4.h': 'Lifestyle', 'f4.p': 'Six cards about life in Port Ghalib.',
   'f5.h': 'Motion', 'f5.p': 'A particle loader, parallax hero, 3D tilt cards and count-up numbers.',
   'f6.h': 'Share-ready', 'f6.p': 'A custom preview image for WhatsApp and social media, and it saves to the iPhone home screen.',
   'n1': 'Projects', 'n2': 'Villas', 'n3': 'Units available', 'n4': 'Red Sea shoreline',
   'c1': 'Navy', 'c2': 'Teal', 'c3': 'Orange', 'c4': 'Off-white',
  },
  'ar': {
   'type': 'بورتفوليو لمسؤول مبيعات',
   'lede': 'بورتفوليو شخصي لمشرف مبيعات عقارية في لاريمار بورت غالب: المشروعات وأسلوب الحياة وأسباب الاستثمار.',
   'client': 'محمد شعراوي · لاريمار', 'where': 'بورت غالب، مرسى علم',
   'brief': 'يبيع محمد فيلات وأجنحة في لاريمار لمشترين من الخارج. احتاج رابطًا واحدًا يرسله لكل عميل، يشرح المشروعات ويسهّل طلب الأسعار.',
   'built': 'بورتفوليو أنيق بالكحلي والفيروزي، فيه ثلاث بطاقات للمشروعات، والحياة في بورت غالب، وخمسة أسباب للاستثمار، ونموذج تواصل يرسل رسالة واتساب بالمشروع المختار.',
   'f1.h': 'بطاقات المشروعات', 'f1.p': 'الفيلات والأجنحة ولاريمار 3، لكلٍّ منها المساحات وزر «اطلب السعر».',
   'f2.h': 'استفسارات واتساب', 'f2.p': 'اختر المشروع ويكتب النموذج رسالة واتساب.',
   'f3.h': 'لماذا تستثمر', 'f3.p': 'خمسة أسباب واضحة، من التسليم الكامل والطلب على الإيجار إلى الإدارة الفندقية وخطط السداد.',
   'f4.h': 'أسلوب الحياة', 'f4.p': 'ست بطاقات عن الحياة في بورت غالب.',
   'f5.h': 'الحركة', 'f5.p': 'شاشة تحميل بالجزيئات، وواجهة بتأثير العمق، وبطاقات مائلة ثلاثية الأبعاد، وأرقام تعدّ تصاعديًا.',
   'f6.h': 'جاهز للمشاركة', 'f6.p': 'صورة معاينة خاصة لواتساب ومواقع التواصل، ويُحفظ على الشاشة الرئيسية للآيفون.',
   'n1': 'مشروعات', 'n2': 'فيلا', 'n3': 'وحدة متاحة', 'n4': 'ساحل البحر الأحمر',
   'c1': 'كحلي', 'c2': 'فيروزي', 'c3': 'برتقالي', 'c4': 'أبيض دافئ',
  },
  'de': {
   'type': 'Portfolio für einen Vertriebsleiter',
   'lede': 'Ein persönliches Portfolio für einen Immobilien-Vertriebsleiter bei Larimar, Port Ghalib: die Projekte, das Leben vor Ort und die Gründe zu investieren.',
   'client': 'Mohamed Sharawi · Larimar', 'where': 'Port Ghalib, Marsa Alam',
   'brief': 'Mohamed verkauft Villen und Suiten bei Larimar an Käufer im Ausland. Er brauchte einen Link für jeden Interessenten, der die Projekte erklärt und die Preisanfrage leicht macht.',
   'built': 'Ein klares Portfolio in Marineblau und Türkis mit drei Projektkarten, dem Leben in Port Ghalib, fünf Gründen zu investieren und einem Kontaktformular, das eine WhatsApp-Nachricht mit dem gewählten Projekt sendet.',
   'f1.h': 'Projektkarten', 'f1.p': 'Villas, Suites und Larimar 3, jeweils mit Größen und einem Button „Preis anfragen“.',
   'f2.h': 'Anfragen per WhatsApp', 'f2.p': 'Projekt wählen, und das Formular schreibt die WhatsApp-Nachricht.',
   'f3.h': 'Warum investieren', 'f3.p': 'Fünf klare Gründe, von schlüsselfertiger Übergabe und Mietnachfrage bis Hotelverwaltung und Ratenzahlung.',
   'f4.h': 'Lebensstil', 'f4.p': 'Sechs Karten über das Leben in Port Ghalib.',
   'f5.h': 'Bewegung', 'f5.p': 'Partikel-Ladebildschirm, Parallax-Hero, 3D-Kippkarten und hochzählende Zahlen.',
   'f6.h': 'Bereit zum Teilen', 'f6.p': 'Ein eigenes Vorschaubild für WhatsApp und Social Media, speicherbar auf dem iPhone-Home-Bildschirm.',
   'n1': 'Projekte', 'n2': 'Villen', 'n3': 'Verfügbare Einheiten', 'n4': 'Küste am Roten Meer',
   'c1': 'Marine', 'c2': 'Türkis', 'c3': 'Orange', 'c4': 'Gebrochenes Weiß',
  },
  'it': {
   'type': 'Portfolio per un agente di vendita',
   'lede': 'Un portfolio personale per un supervisore vendite immobiliari a Larimar, Port Ghalib: i progetti, lo stile di vita e i motivi per investire.',
   'client': 'Mohamed Sharawi · Larimar', 'where': 'Port Ghalib, Marsa Alam',
   'brief': 'Mohamed vende ville e suite a Larimar ad acquirenti dall’estero. Gli serviva un unico link da mandare a ogni contatto, che spieghi i progetti e renda facile chiedere i prezzi.',
   'built': 'Un portfolio pulito blu navy e verde acqua, con tre schede progetto, la vita a Port Ghalib, cinque motivi per investire e un modulo che invia un messaggio WhatsApp con il progetto scelto.',
   'f1.h': 'Schede progetto', 'f1.p': 'Villas, Suites e Larimar 3, ognuna con metrature e un pulsante “Richiedi prezzi”.',
   'f2.h': 'Richieste su WhatsApp', 'f2.p': 'Scegli un progetto e il modulo scrive il messaggio WhatsApp.',
   'f3.h': 'Perché investire', 'f3.p': 'Cinque motivi chiari, dalla consegna chiavi in mano e la domanda di affitti alla gestione alberghiera e ai pagamenti rateali.',
   'f4.h': 'Stile di vita', 'f4.p': 'Sei schede sulla vita a Port Ghalib.',
   'f5.h': 'Movimento', 'f5.p': 'Loader a particelle, hero in parallasse, card inclinabili in 3D e numeri che contano.',
   'f6.h': 'Pronto da condividere', 'f6.p': 'Un’immagine di anteprima per WhatsApp e i social, e si salva sulla schermata Home dell’iPhone.',
   'n1': 'Progetti', 'n2': 'Ville', 'n3': 'Unità disponibili', 'n4': 'Costa sul Mar Rosso',
   'c1': 'Navy', 'c2': 'Verde acqua', 'c3': 'Arancio', 'c4': 'Bianco caldo',
  },
 },
]
